# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(default=None, max_length=255, null=True)),
                ('lastname', models.CharField(default=None, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('phonenumber', models.IntegerField(default=0)),
                ('address', models.TextField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
